version: '2'
services:
  database:
    image: mysql:5.7
    container_name: otsuge-database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - ./data:/usr/src/data

  server:
    image: otsuge
    container_name: otsuge-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: 'development'
      DATABASE_URL: mysql2://root@database:3306
    ports:
      - '3000:3000'
    links:
      - database
    volumes:
      - .:/usr/src/app
